---

spring:
  profiles:
    include: h2

---

spring:
  profiles: h2
  datasource:
    url: jdbc:h2:mem:wehaul;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console


---

spring:
  profiles: postgresql
  datasource:
    url: jdbc:postgresql://localhost/wehaul
    username: ${user.name}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: true
